### ISSUE TITLE
If there is a split type of the dataset

### ISSUE THREAD

**Issue by Alice-6161** [testingautomated-usi/fashion-mnist-c#2]
Thanks to your design of fashion-minist-c, I wonder if I can get the dataset according to their particular corruption type.

**Comment by MiWeiss** [comment]
Excuse my late reply - I have not noticed this issue...

With the currently released datasets, I am afraid this is not easily possible.

However, it should be easily possible to adapt the [generator script](https://github.com/testingautomated-usi/fashion-mnist-c/blob/main/generator.py) to give you corruptions for a specific types.
